apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: starwars
data:
  script.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      stages: [
        { duration: '30s', target: 20 },
        { duration: '2m', target: 100 },
        { duration: '1m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<500'],
      },
    };

    export default function () {
      const res = http.get('http://back-cluster-ip-service:4000/');
      check(res, {
        'status was 200': (r) => r.status == 200,
      });
      sleep(0.1);
    }
