apiVersion: v1
kind: ConfigMap # Non-sensitive configuration for the application
metadata:
  name: back-configmap # ConfigMap for backend settings
  namespace: starwars
data:
  # --- Backend Configuration ---
  ROOT_PATH: "/api"
  SWAPI_ENTRYPOINT: "https://swapi.dev/api"
  # Database Connection Params (Non-sensitive)
  PGHOST: "postgres-cluster-ip-service"
  PGPORT: "5432"
  PGUSER: "postgres"
  PGDATABASE: "postgres"
