apiVersion: v1
kind: ConfigMap # Non-sensitive configuration for the application
metadata:
  name: front-configmap # ConfigMap for frontend settings
  namespace: starwars
data:
  # --- Frontend Configuration ---
  API_URL: "http://back:4000"
