# --- Canary Route for Backend API ---
# This overwrites the standard 'jedy-api-route' to add traffic splitting.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jedy-api-route # SAME NAME to overwrite the existing route
  namespace: starwars
spec:
  parentRefs:
  - name: infra-gateway
    namespace: gateways
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: back-service
      port: 4000
      weight: 90 # 90% to V1
      # weight: 50 # 50% to V1
      # weight: 0 # 0% to V1
    - name: back-v2-service
      port: 4000
      weight: 10 # 10% to V2
      # weight: 50 # 50% to V2
      # weight: 100 # 100% to V2
